### ISSUE TITLE
Dark Light Theme

### ISSUE THREAD

**Issue by harshmetkel24** [harshmetkel24/pricehistory#1]
Add new button to navbar to toggle between light and dark theme. Keep the navbar response for mobile devices.

**Comment by harshmetkel24** [comment]
give @Dharmesh-Kota 150 points

**Comment by Dharmesh-Kota** [comment]
Can I implement this feature!!

**Comment by harshmetkel24** [comment]
give @Dharmesh-Kota 150 points

**Comment by harshmetkel24** [comment]
give @Dharmesh-Kota 150 points

**Comment by harshmetkel24** [comment]
Dark Theme toggle feature done, hence issue stands closed now.

**Comment by harshmetkel24** [comment]
Dark light theme defaults to light theme on page navigation

**Comment by harshmetkel24** [comment]
bug fixed by @Dharmesh-Kota

**Comment by harshmetkel24** [comment]
give @Dharmesh-Kota 25 points

**Comment by harshmetkel24** [comment]
reopening because of some issues with webhooks

**Comment by harshmetkel24** [comment]
give @Dharmesh-Kota 50 points
