### ISSUE TITLE
Code Refactoring

### ISSUE THREAD

**Issue by harshmetkel24** [harshmetkel24/pricehistory#4]

**Comment by Dharmesh-Kota** [comment]
I can refactor the code using express-ejs-layouts which will remove repetitive codes and also it will make code more readable. Please assign this issue to me.

**Comment by harshmetkel24** [comment]
Yess you can start working on it.

**Comment by harshmetkel24** [comment]
give @Dharmesh-Kota 150 points

**Comment by harshmetkel24** [comment]
give @Dharmesh-Kota 150 points

**Comment by harshmetkel24** [comment]
Code refactoring has been done, hence issue stands closed now.
